### PR TITLE
Add k8s DNS tests

### PR DESCRIPTION
**Pull request by galal-hussein**
Add automation to DNS k8s test cases except for Petsets:

https://github.com/rancherlabs/the-ranch/wiki/DNS-Kubernetes-Test-Cases

### CODE REVIEW

**Comment by sangeethah** [comment]
@galal-hussein , As part of DNS validation , can we also make sure we are able to connect using these DNS names?

**Comment by galal-hussein** [comment]
@sangeethah The latest commit will test for connectivity using DNS names

**Comment by galal-hussein** [comment]
@sangeethah The latest commit removes (admin_client, client) and uses kubectl instead of exec into containers, also it checks for names of the pod using wget.

**Comment by sangeethah** [comment]
LGTM

**Pull request merged**
