### PR TITLE
Added new ingress tests and associated resource files

### PR DESCRIPTION
**Pull request by soumyalj**
@sangeethah : Added new ingress tests. Please review when you get a chance.

### CODE REVIEW

**Comment by sangeethah** [comment]
@soumyalj , can we move the service files related to ingress tests to corresponding ingress files , since we don't seem to be sharing the same services across different ingress tests ?

**Comment by sangeethah** [comment]
Also there should be no need for client and admin_clients for k8s tests. Can this be removed?

**Comment by soumyalj** [comment]
@sangeethah : I removed the admin_client from the K8 tests. I need client for one of the tests `test_k8s_ingress_23` as we need to add labels to the hosts, verify the ingress is scheduled on the host with the desired label and remove the labels.

Will combine ingress and service files to a single file as a separate task.

**Comment by sangeethah** [comment]
LGTM

**Pull request merged**
