### PR TITLE
Added testcase for creating pod with private registry image (test_k8s…

### PR DESCRIPTION
**Pull request by soumyalj**
…_env_create_pod_with_private_registry_image)

@sangeethah : Please take a look.

### CODE REVIEW

**Comment by sangeethah** [comment]
@soumyalj , we should not be executing this test case , when parameters relating to private registry is not passed. Make sure that these test cases get skipped when private registry parameters are not available.

**Comment by sangeethah** [comment]
Also cab u include include the yml  file needed for this test?

**Comment by soumyalj** [comment]
@sangeethah : Handled test case skip and also checked in the yml file

**Comment by sangeethah** [comment]
LGTM

**Pull request merged**
