### PR TITLE
Tests for AD porting

### PR DESCRIPTION
**Pull request by mrajashree**
AD porting to auth-service has changed some api calls for the tests.

### CODE REVIEW

**Comment by mrajashree** [comment]
```
export API_AUTH_AD_SERVER='tad.rancher.io'
export API_AUTH_AD_PORT=389
export API_AUTH_AD_SERVICE_ACCOUNT_USERNAME='TAD\sauser'
export API_AUTH_AD_SERVICE_ACCOUNT_PASSWORD='Password1'
export API_AUTH_AD_LOGIN_DOMAIN='TAD'
export API_AUTH_AD_SEARCH_BASE='dc=tad,dc=rancher,dc=io'
export SCHEMA_AD_USER_OBJECT_CLASS=person
export SCHEMA_AD_USER_LOGIN_FIELD=sAMAccountName
export SCHEMA_AD_USER_NAME_FIELD=name
export SCHEMA_AD_USER_SEARCH_FIELD=sAMAccountName
export SCHEMA_AD_USER_STATUS_FIELD=userAccountControl
export SCHEMA_AD_USER_DISABLED_STATUS_BITMASK=2
export SCHEMA_AD_GROUP_OBJECT_CLASS=group
export SCHEMA_AD_GROUP_NAME_FIELD=name
export SCHEMA_AD_GROUP_MEMBER_USER_ATTRIBUTE=""
export SCHEMA_AD_GROUP_DN_FIELD=""
export SCHEMA_AD_GROUP_SEARCH_FIELD=sAMAccountName
export AD_MAIN_USER=testuser1
export AD_MAIN_PASS=Password1
export AD_USER2=testuser2
export AD_PASS2=Password1
export AD_USER3=testuser3
export AD_PASS3=Password1
export AD_USER4=testuser4
export AD_PASS4=Password1
export AD_GROUP=testsecuritygroup1
export DIGITALOCEAN_KEY=
```
The config I used for testing with AD setup.

test_ldap_auth.py is renamed to test_openldap_auth.py and would work for openldap setup.

**Comment by sangeethah** [comment]
@mrajashree , With Ldap porting, test_ad_group_search_domain  should not need enable and disable of auth services to change group_search_base .

Also can you parameterize the SEARCH_BASE and GROUP_SEARCH_BASE that is being hardcoded now ?

**Comment by sangeethah** [comment]
This test case needs to be skipped when DO access key is not provided -test_ad_create_new_env_with_readonly_member

**Comment by sangeethah** [comment]
Can we also add test cases for service account password to be not returned for AD and LDAP:
v2-beta/settings/api.auth.ldap.service.account.password -> returns null
v2-beta/settings/api.auth.ldap.openldap.service.account.password -> returns null

**Comment by sangeethah** [comment]
@mrajashree , following test fails when trying to add digital ocean host -cattlevalidationtest.core.test_ldap_auth.test_ad_member_add_host 

```
                                     project_id=project.id)
        # Add new host
        host_list = \
            add_digital_ocean_hosts(
>               u2_client, 1)

tests/v2_validation/cattlevalidationtest/core/test_ldap_auth.py:1366: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/v2_validation/cattlevalidationtest/core/common_fixtures.py:2968: in add_digital_ocean_hosts
    host = client.wait_success(host, timeout=DEFAULT_MACHINE_TIMEOUT)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cattle.Client object at 0x7fa20e0f5c50>
obj = {'localStorageMb': None, 'createdTS': 1502255839000, 'engineOpt': None, 'labels': None, 'agentState': None, 'authCerti...ineEnv': None, 'engineRegistryMirror': None, 'amazonec2Config': None, 'engineStorageDriver': None, 'instanceIds': None}
timeout = 900

    def wait_success(self, obj, timeout=-1):
        obj = self.wait_transitioning(obj, timeout)
        if obj.transitioning != 'no':
>           raise gdapi.ClientApiError(obj.transitioningMessage)
E           ClientApiError: Error with pre-create check: "invalid character '\\\\' looking for beginning of object key string"

/usr/local/lib/python2.7/dist-packages/cattle.py:17: ClientApiError
```
test_secret_setting test reports  "Pass" when tested on setup with LDAP_PORT set to "false". Instead , this test needs to be skipped.

**Comment by mrajashree** [comment]
@sangeethah This error ` ClientApiError: Error with pre-create check: "invalid character '\\\\' looking for beginning of object key string"` doesn't seem auth related. Maybe I'll try running this test manually to see what happens.
For `test_secret_setting`, I was retuning from the test without doing anything if LDAP_PORT is false. I'll make it skip instead

**Comment by sangeethah** [comment]
LGTM

**Pull request merged**
